config/routes.rb
Rails.application.routes.draw do
  
  resources :pois do
    get :by_distance_show, on: :collection
    get :by_distance_search, on: :collection
  end
  get 'static_pages/home'
  
  root 'static_pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poi.rb
class Poi < ApplicationRecord
    validates :name, presence: true, length: {minimum:3 }
    validates :x, presence: true, 
        numericality: { only_integer: true,
                        greater_than: 0 }
    validates :x, presence: true, 
        numericality: { only_integer: true,
        greater_than: 0 }

    scope :elect_pois_by_max_dist, ->(x,y,max_dist) {
        where("sqrt(pow((? - x),2) + pow((? - y),2)) <= ?", x,y, max_dist)
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
    def new
        @poi = Poi.new
    end

    def index
        @pois = Poi.all
    end

    def create
        @poi = Poi.new(poi_params)
        if @poi.save
            redirect_to @poi
        else
            render 'new'
        end
    end

    
    
    def by_distance_show
        @poivalidator = PoiValidator.new(
            x: params[:x], y: params[:y], max_dist: params[:max_dist])
        if @poivalidator.valid? 
            x = params[:x].to_i
            y = params[:y].to_i
            max_dist = params[:max_dist].to_i
            @elected_pois = Poi.elect_pois_by_max_dist(x,y,max_dist)
            render 'pois-by-distance-list'
        else
            render 'pois-by-distance'
        end
    end

    def by_distance_search
        @poivalidator = PoiValidator.new
        render 'pois-by-distance'
    end

    def show
        @poi = Poi.find(params[:id])
    end

    def destroy
        @poi = Poi.find(params[:id])
        @poi.destroy

        redirect_to pois_path
    end

    private
        def poi_params
            params.require(:poi).permit(:name, :x, :y)
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pois_helper.rb
module PoisHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XyPois</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pois/_form.html.erb
<%= form_with model: :@poi, url: points_of_interest_path, local: true do |form| %>
    <% if @poi.error.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@poi.errors.count, "error") %> prohibited
            </h2>
        </div>
        <ul>
            <% @article.errors.full_messages. each do |msg|%>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    <p>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </p>
    <p>
        <%= form.label :x %>
        <%= form.number_field :x %>
    </p>
    <p>
        <%= form.label :y %>
        <%= form.number_field :y %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/pois/index.html.erb
<h1>Listing all points of interest</h1>
<p>
    <%= link_to "New POI", new_poi_path %> | 
    <%= link_to "Nearby POIs by distance", by_distance_search_pois_path %>
</P>
<table>
    <tr>
        <th>Name</th>
        <th>X</th>
        <th>Y</th>
    </tr>
    <% @pois. each do |poi|%>
        <tr>
            <td><%= poi.name %></td>
            <td><%= poi.x %></td>
            <td><%= poi.y %></td>
            <td><%= link_to 'Show', poi_path(poi) %> | </td>
            <td><%= link_to 'Destroy', poi_path(poi), 
                            method: :delete,
                            data: { confirm: 'Are you sure?' }%></td>
        </tr>
    <% end %>
</table>

app/views/pois/new.html.erb
<h1>New POI</h1>

<%= form_with scope: :poi, url: pois_path, 
local: true do |form| %>
    <% if @poi.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@poi.errors.count, "error") %> prohibited
            </h2>
        </div>
        <ul>
            <% @poi.errors.full_messages. each do |msg|%>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    <p>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </p>
    <p>
        <%= form.label :x %>
        <%= form.number_field :x %>
    </p>
    <p>
        <%= form.label :y %>
        <%= form.number_field :y %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/pois/pois-by-distance-list.html.erb
<h1>Listing all POIs in the range</h1>
<p>
    <%= link_to "Back", pois_path %> | 
    <%= link_to "Another search", by_distance_search_pois_path %>
<table>
    <tr>
        <th>Name</th>
        <th>X</th>
        <th>Y</th>
    </tr>
    <% @elected_pois.each do |poi|%>
        <tr>
            <td><%= poi.name %></td>
            <td><%= poi.x %></td>
            <td><%= poi.y %></td>
        </tr>
    <% end %>
</table>

app/views/pois/pois-by-distance.html.erb
<%= form_for(@poivalidator, :url =>{ :action => "by_distance_show" }, method: "get") do %>
    <% if @poivalidator.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@poivalidator.errors.count, "error") %> prohibited
            </h2>
        </div>
        <ul>
            <% @poivalidator.errors.full_messages. each do |msg|%>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    
    <p>
        <%= label_tag(:max_dist, "Distância Máxima: ")%>
        <%= text_field_tag(:max_dist) %>
    </p>
    <p>
        <%= label_tag(:x, "X: ")%>
        <%= text_field_tag(:x) %>
    </p>
    <p>
        <%= label_tag(:y, "Y: ")%>
        <%= text_field_tag(:y) %>
    </p>
    <%= submit_tag("Search") %>
<% end %>

app/views/pois/show.html.erb
<p>
    <strong>Name: </strong>
    <%= @poi.name %>
</p>
<p>
    <strong>X: </strong>
    <%= @poi.x %>
</p>
<p>
    <strong>Y: </strong>
    <%= @poi.y %>
</p>
<%= link_to 'Back to Index', pois_path %>
<%= link_to 'New POI', new_poi_path %>

app/views/static_pages/home.html.erb
<h1>POI</h1>
<p>Find your points of interest</p>
<%= link_to 'List all POIs', pois_path %>